### ISSUE TITLE
REST clarification

### ISSUE THREAD

**Issue by niVelion** [chaincodelabs/bitcoin-core-onboarding#4]
https://github.com/chaincodelabs/bitcoin-core-onboarding/blob/main/1.0_bitcoin_core_architecture.asciidoc#L35

> To start a node, just run the main app bitcoind implemented in src/bitcoind.cpp. This executable is expected to run as a daemon (in the background). It also provides a REST interface, so anyone authorized can access and work with the node.

[Bitcoin Core documentation for the REST interface](https://github.com/bitcoin/bitcoin/blob/master/doc/REST-interface.md) makes clear this is an unauthenticated interface, and later in the document twice mentions localhost, which I presume means that when enabled it will by default listen on `127.0.0.1:8332`, where the first half represents the `localhost` network interface.

This network interface is only accessible on the localhost, but is otherwise unauthenticated.

Thumbs up and I'll open a PR with this rewording.

> To start a node, just run the main app bitcoind implemented in src/bitcoind.cpp. This executable is expected to run as a daemon (in the background). When passing the command line option `-rest`, it also provides an unauthenticated REST interface, which by default listens on 127.0.0.1:8332.

**Comment by adamjonas** [comment]
ref #5
